export interface Template {
  id: string;
  title: string;
  category: "closet" | "pantry" | "laundry" | "garage" | "more";
  imageUrl: string;
  description: string;
  starterPrompt: string;
  spaceType: string;
  style: string;
  finish: string;
  components: string[];
}

export const CATEGORIES = ["All", "Closet", "Pantry", "Laundry", "Garage", "More Spaces"] as const;

export const TEMPLATES: Template[] = [
  // Closet
  {
    id: "1",
    title: "Modern Walk-in Closet",
    category: "closet",
    imageUrl: "/templates/1-modern-walk-in-closet.webp",
    description: "Clean lines and geometric shelving with matte hardware for a sleek, contemporary feel.",
    starterPrompt: "I want a modern walk-in closet with clean geometric lines, matte gray flat-panel cabinetry in a Clay finish, matte black hardware, LED strip lighting along the shelves, double hanging rods, and angled shoe displays.",
    spaceType: "walk-in closet",
    style: "modern",
    finish: "Clay",
    components: ["double hanging rods", "LED strip lighting", "shoe shelves", "flat-panel drawers"],
  },
  {
    id: "2",
    title: "Minimalist Reach-in",
    category: "closet",
    imageUrl: "/templates/2-minimalist-reach-in.webp",
    description: "A streamlined reach-in closet that maximizes every inch with simple, open shelving.",
    starterPrompt: "I want a minimalist reach-in closet with crisp White finish, open adjustable shelves, a single hanging rod, slim pull-out drawers, and clean uncluttered lines that make a small space feel bigger.",
    spaceType: "reach-in closet",
    style: "minimalist",
    finish: "White",
    components: ["adjustable shelves", "single hanging rod", "pull-out drawers"],
  },
  {
    id: "3",
    title: "Luxury Wardrobe",
    category: "closet",
    imageUrl: "/templates/3-luxury-wardrobe.webp",
    description: "Rich Espresso cabinetry with glass-front doors and a center island for a high-end dressing room experience.",
    starterPrompt: "I want a luxury walk-in closet with rich Espresso finish cabinetry, glass-front display doors, a center island with velvet-lined jewelry drawers, crown molding, recessed LED lighting, and dedicated sections for bags and accessories.",
    spaceType: "walk-in closet",
    style: "traditional",
    finish: "Espresso",
    components: ["glass-front doors", "center island", "jewelry drawers", "crown molding", "LED lighting"],
  },
  {
    id: "10",
    title: "His & Hers Walk-in",
    category: "closet",
    imageUrl: "/templates/10-his-and-hers-walk-in.webp",
    description: "A shared walk-in with mirrored sides giving each person their own organized zone.",
    starterPrompt: "I want a his-and-hers walk-in closet with symmetrical mirrored sides in Chateau finish, double hanging rods on each side, a shared center island with drawers, built-in hampers, full-length mirrors, and soft overhead lighting.",
    spaceType: "walk-in closet",
    style: "transitional",
    finish: "Chateau",
    components: ["double hanging rods", "center island", "built-in hampers", "full-length mirrors"],
  },
  {
    id: "11",
    title: "Kids' Reach-in Closet",
    category: "closet",
    imageUrl: "/templates/11-kids-reach-in-closet.webp",
    description: "Kid-friendly heights with colorful bins and adjustable rods that grow with your child.",
    starterPrompt: "I want a kids' reach-in closet with White finish, low-mounted hanging rods they can reach, colorful open bins for toys, adjustable shelves that can grow with them, and a top shelf for seasonal storage.",
    spaceType: "reach-in closet",
    style: "modern",
    finish: "White",
    components: ["low hanging rods", "open bins", "adjustable shelves", "top shelf storage"],
  },
  {
    id: "12",
    title: "Boutique-Style Closet",
    category: "closet",
    imageUrl: "/templates/12-boutique-style-closet.webp",
    description: "A glamorous display closet with lit shelving and glass doors that feels like a high-end shop.",
    starterPrompt: "I want a boutique-style walk-in closet with White finish, glass-front display shelves with LED backlighting, acrylic drawer fronts, a vanity area with mirror and stool, open shoe display wall, and polished chrome hardware.",
    spaceType: "walk-in closet",
    style: "glam",
    finish: "White",
    components: ["glass-front shelves", "LED backlighting", "vanity area", "shoe display wall", "chrome hardware"],
  },

  // Pantry
  {
    id: "4",
    title: "Organized Pantry",
    category: "pantry",
    imageUrl: "/templates/4-organized-pantry.webp",
    description: "A well-structured pantry with labeled zones for dry goods, snacks, and small appliances.",
    starterPrompt: "I want an organized pantry with White finish shelving, clear-front bins for dry goods, pull-out basket drawers, dedicated zones for canned goods, snacks, and small appliances, with LED under-shelf lighting.",
    spaceType: "pantry",
    style: "modern",
    finish: "White",
    components: ["adjustable shelves", "pull-out baskets", "clear-front bins", "LED under-shelf lighting"],
  },
  {
    id: "5",
    title: "Pull-out Pantry Shelves",
    category: "pantry",
    imageUrl: "/templates/5-pull-out-pantry-shelves.webp",
    description: "Deep pull-out shelves on smooth glides that bring everything to you — no more digging.",
    starterPrompt: "I want a pantry with Ivory finish pull-out shelves on full-extension glides, tiered spice racks on the door backs, a wine rack section, and soft-close drawers for utensils and linens.",
    spaceType: "pantry",
    style: "transitional",
    finish: "Ivory",
    components: ["pull-out shelves", "tiered spice racks", "wine rack", "soft-close drawers"],
  },
  {
    id: "13",
    title: "Butler's Pantry",
    category: "pantry",
    imageUrl: "/templates/13-butlers-pantry.webp",
    description: "An elegant butler's pantry with glass-front uppers and countertop prep space between kitchen and dining.",
    starterPrompt: "I want a butler's pantry with Espresso finish cabinetry, glass-front upper cabinets for displaying china, a countertop prep area, wine storage, soft-close drawers for silverware, and warm overhead pendant lighting.",
    spaceType: "pantry",
    style: "traditional",
    finish: "Espresso",
    components: ["glass-front uppers", "countertop prep area", "wine storage", "soft-close drawers"],
  },

  // Laundry
  {
    id: "6",
    title: "Laundry Room Storage",
    category: "laundry",
    imageUrl: "/templates/6-laundry-room-storage.webp",
    description: "Smart shelving above and beside the machines with a folding counter and sorting bins.",
    starterPrompt: "I want a laundry room with White finish storage cabinets above the washer and dryer, a folding counter, pull-out sorting hampers, adjustable shelves for detergent and supplies, and a hanging rod for air-drying.",
    spaceType: "laundry room",
    style: "modern",
    finish: "White",
    components: ["upper cabinets", "folding counter", "pull-out hampers", "hanging rod", "adjustable shelves"],
  },
  {
    id: "7",
    title: "Compact Laundry Nook",
    category: "laundry",
    imageUrl: "/templates/7-compact-laundry-nook.webp",
    description: "Maximize a tight space with stacked machines and slim vertical shelving.",
    starterPrompt: "I want a compact laundry nook with White finish, slim vertical shelving beside a stacked washer-dryer, a fold-down ironing board, a narrow pull-out hamper, and wall-mounted drying rack.",
    spaceType: "laundry room",
    style: "minimalist",
    finish: "White",
    components: ["vertical shelving", "fold-down ironing board", "pull-out hamper", "wall-mounted drying rack"],
  },
  {
    id: "14",
    title: "Laundry + Mudroom Combo",
    category: "laundry",
    imageUrl: "/templates/14-laundry-mudroom-combo.webp",
    description: "A dual-purpose space with coat hooks, boot storage, and laundry essentials in rustic Driftwood.",
    starterPrompt: "I want a laundry and mudroom combo in farmhouse style with Driftwood finish, open cubbies with coat hooks, a storage bench with shoe compartments below, upper cabinets for laundry supplies, and a folding counter.",
    spaceType: "laundry room",
    style: "farmhouse",
    finish: "Driftwood",
    components: ["coat hooks", "storage bench", "shoe compartments", "upper cabinets", "folding counter"],
  },

  // Garage
  {
    id: "8",
    title: "Garage Wall System",
    category: "garage",
    imageUrl: "/templates/8-garage-wall-system.webp",
    description: "Heavy-duty wall-mounted panels with hooks, shelves, and bins to get everything off the floor.",
    starterPrompt: "I want a garage wall storage system in industrial style with Lava finish, heavy-duty slatwall panels, adjustable hooks for tools and bikes, metal shelving for bins, a fold-down workbench, and overhead ceiling storage.",
    spaceType: "garage",
    style: "industrial",
    finish: "Lava",
    components: ["slatwall panels", "adjustable hooks", "metal shelving", "fold-down workbench"],
  },
  {
    id: "9",
    title: "Garage Ceiling Storage",
    category: "garage",
    imageUrl: "/templates/9-garage-ceiling-storage.webp",
    description: "Overhead racks and hoists to store seasonal gear and free up floor and wall space.",
    starterPrompt: "I want a garage with overhead ceiling storage racks in White finish, motorized hoists for bikes and kayaks, heavy-duty wire shelving along the walls, labeled bins for seasonal items, and bright LED overhead lighting.",
    spaceType: "garage",
    style: "industrial",
    finish: "White",
    components: ["ceiling storage racks", "motorized hoists", "wire shelving", "labeled bins", "LED lighting"],
  },
  {
    id: "15",
    title: "Workshop Garage",
    category: "garage",
    imageUrl: "/templates/15-workshop-garage.webp",
    description: "A serious workspace with a solid workbench, tool pegboard, and dedicated power-tool storage.",
    starterPrompt: "I want a workshop garage in industrial style with Lava finish, a full-length solid workbench, pegboard tool wall with outlined tool positions, heavy-duty cabinets for power tools, a vise station, and bright task lighting.",
    spaceType: "garage",
    style: "industrial",
    finish: "Lava",
    components: ["workbench", "pegboard tool wall", "heavy-duty cabinets", "vise station", "task lighting"],
  },

  // More Spaces
  {
    id: "16",
    title: "Mudroom Entryway",
    category: "more",
    imageUrl: "/templates/16-mudroom-entryway.webp",
    description: "A warm farmhouse entry with cubbies, hooks, and a bench to keep coats, shoes, and bags organized.",
    starterPrompt: "I want a mudroom entryway in farmhouse style with Sierra finish, individual cubbies with hooks for each family member, a storage bench with shoe compartments, wainscoting detail, upper cabinets, and a rustic warm tone.",
    spaceType: "entryway",
    style: "farmhouse",
    finish: "Sierra",
    components: ["individual cubbies", "coat hooks", "storage bench", "shoe compartments", "upper cabinets"],
  },
  {
    id: "17",
    title: "Home Office Storage",
    category: "more",
    imageUrl: "/templates/17-home-office-storage.webp",
    description: "A built-in office nook with bookshelves, file drawers, and a clean desktop surface.",
    starterPrompt: "I want a home office with modern built-in storage in Desert finish, floor-to-ceiling bookshelves flanking a desk nook, file drawers, cable management, open display shelves for decor, and warm LED task lighting.",
    spaceType: "home office",
    style: "modern",
    finish: "Desert",
    components: ["bookshelves", "desk nook", "file drawers", "cable management", "display shelves"],
  },
  {
    id: "18",
    title: "Craft Room Organizer",
    category: "more",
    imageUrl: "/templates/18-craft-room-organizer.webp",
    description: "A creative workspace with cubbies for supplies, a large work surface, and ribbon and paper racks.",
    starterPrompt: "I want a craft room organizer in transitional style with Ivory finish, a large work table in the center, wall-mounted cubbies for fabric and paper, ribbon racks, pull-out trays for tools, a pegboard inspiration wall, and bright even lighting.",
    spaceType: "craft room",
    style: "transitional",
    finish: "Ivory",
    components: ["work table", "wall-mounted cubbies", "ribbon racks", "pull-out trays", "pegboard wall"],
  },
];
